import "./globals.css";
import { Source_Sans_3 } from "next/font/google";

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Star Wars Challenge || Rafael Thumaza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={sourceSans.className}>{children}</body>
    </html>
  );
}
